### ISSUE TITLE
variables across chapters

### ISSUE THREAD

**Issue by ShanEllis** [jhudsl/tidyversecourse#3]
Just as a general note that variables created in one chapter are not available in others, which becomes problematic for case studies. (For example, we want the tidied data frame to be available for visualization.) 

We can create a separate package if needed (or put everything on one giant R Markdown -yikes!) to avoid this issue, so that the book compiles...which it currently does not.

Just wanted to put this one everyone's radar as something we'll have to discuss.

**Comment by stephaniehicks** [comment]
oooh good point. Let's talk about it on Tuesday?

**Comment by ShanEllis** [comment]
Ya! I can't make it this Tuesday b/c we're moving into our new house (!) but should be able to make most weeks and have the standing meeting in my calendar.

**Comment by carriewright11** [comment]
resolved
