### ISSUE TITLE
No license (file) ?

### ISSUE THREAD

**Issue by SamGuay** [jhudsl/tidyversecourse#6]
Hello, 

I'd like to re-use some content of this book for one of the class I teach but I can't find any license file in the repo. I've browsed your other courses and repos and I noticed you moved from MIT to CC-BY for a couple of them. For example, I was able to find a CC-BY license for the [Computing for Cancer Informatics](https://github.com/jhudsl/Computing_for_Cancer_Informatics) course.

Since I can't find whether this repo is under a CC-BY or any license, I am asking just to make sure. 

Thanks

**Comment by carriewright11** [comment]
Hi @SamGuay! Thanks for reaching out about this. It took some time for all of the authors to meet about this. We decided to use a [CC-BY-NC](https://creativecommons.org/licenses/by-nc/4.0/) license for this material.

**Comment by SamGuay** [comment]
Great, thank you!
